# Generated by Django 5.1.5 on 2025-01-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighting_color', models.CharField(default='white', max_length=100)),
                ('sound_level', models.PositiveIntegerField(default=5)),
                ('scent_level', models.PositiveIntegerField(default=5)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambiance', to='devices.room')),
            ],
        ),
        migrations.CreateModel(
            name='AmbianceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_type', models.CharField(choices=[('lighting', 'Lighting'), ('sound', 'Sound'), ('scent', 'Scent')], max_length=100)),
                ('ambiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiance_devices', to='ambiance.ambiance')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiance_controlled', to='devices.device')),
            ],
        ),
    ]
