# Generated by Django 5.1.5 on 2025-01-24 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0001_initial'),
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiancedevice',
            name='ambiance',
        ),
        migrations.RemoveField(
            model_name='ambiancedevice',
            name='device',
        ),
        migrations.CreateModel(
            name='AmbianceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='devices.room')),
            ],
        ),
        migrations.CreateModel(
            name='AmbianceModeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_color', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_by_modes', to='devices.device')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='ambiance.ambiancemode')),
            ],
        ),
        migrations.DeleteModel(
            name='Ambiance',
        ),
        migrations.DeleteModel(
            name='AmbianceDevice',
        ),
    ]
