# Generated by Django 5.1.5 on 2025-01-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0002_remove_ambiancedevice_ambiance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiancemodedevice',
            name='temperature',
            field=models.FloatField(default='24.0'),
        ),
    ]
