# Generated by Django 5.1.5 on 2025-01-28 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0003_alter_ambiancemodedevice_temperature'),
        ('devices', '0008_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiancemodedevice',
            name='light_color',
        ),
        migrations.RemoveField(
            model_name='ambiancemodedevice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ambiancemodedevice',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='ambiancemodedevice',
            name='volume',
        ),
        migrations.AddField(
            model_name='ambiancemode',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='off', max_length=50),
        ),
        migrations.AddField(
            model_name='ambiancemodedevice',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ambiancemodedevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_by_mode', to='devices.device'),
        ),
    ]
