# Generated by Django 5.1.6 on 2025-02-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicesharing', '0002_listing_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('old', 'Old'), ('new', 'New'), ('average', 'Average')], default='average', max_length=50),
        ),
    ]
