# Generated by Django 5.1.5 on 2025-01-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='address',
        ),
    ]
