# Generated by Django 5.1.5 on 2025-01-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='device',
            name='device_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
