# Generated by Django 5.1.5 on 2025-01-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_manufacturer_device_device_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='average_energy_consumption_per_hour',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='general_product_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('idle', 'Idle'), ('error', 'Error')], default='off', max_length=50),
        ),
    ]
