# Generated by Django 5.1.5 on 2025-01-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('error', 'Error')], default='off', max_length=50),
        ),
        migrations.CreateModel(
            name='FixedOptionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[], default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_device', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[], default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_device', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='VariableOptionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=25)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_device', to='devices.device')),
            ],
        ),
    ]
