# Generated by Django 5.1.5 on 2025-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_device_status_fixedoptiondevice_monitordevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
