# Generated by Django 5.1.6 on 2025-02-14 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorFixedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[], default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorfixed_device', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorVariableDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=25)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorvariable_device', to='devices.device')),
            ],
        ),
        migrations.DeleteModel(
            name='MonitorDevice',
        ),
    ]
