# Generated by Django 5.1.5 on 2025-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_time', models.TimeField()),
                ('devices_off', models.ManyToManyField(related_name='automations_off', to='devices.device')),
                ('devices_on', models.ManyToManyField(related_name='automations_on', to='devices.device')),
            ],
        ),
    ]
