# Generated by Django 5.1.5 on 2025-01-18 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('energy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('HOME', 'home'), ('BUSINESS', 'business')], max_length=8)),
                ('energy_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='energy.energygoal')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.house')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guest_code', models.CharField(max_length=255, unique=True)),
                ('allowed_rooms', models.ManyToManyField(to='devices.room')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='users.homeowner')),
            ],
        ),
    ]
