# Generated by Django 5.1.5 on 2025-01-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_owner_business_or_not_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='unique_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='guest',
            old_name='host',
            new_name='owner',
        ),
    ]
