# Generated by Django 5.1.5 on 2025-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_guest_code_alter_guest_name_alter_guest_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
