# Generated by Django 5.1.5 on 2025-01-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_guest_name_guest_house_id_guest_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
