# Generated by Django 5.1.5 on 2025-01-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
        ('users', '0007_alter_guest_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='allowed_rooms',
            field=models.ManyToManyField(related_name='guests', to='devices.room'),
        ),
        migrations.AddField(
            model_name='guest',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
