# Generated by Django 5.1.5 on 2025-01-24 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(choices=[('time', 'Time'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=50)),
                ('trigger_value', models.CharField(max_length=100)),
                ('devices', models.ManyToManyField(related_name='automations', to='devices.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='devices.room')),
            ],
        ),
    ]
