# Generated by Django 5.1.5 on 2025-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_automation_room'),
        ('devices', '0006_remove_device_id_device_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='trigger_type',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='trigger_value',
        ),
        migrations.AddField(
            model_name='automation',
            name='devices_off',
            field=models.ManyToManyField(related_name='automations_off', to='devices.device'),
        ),
        migrations.AddField(
            model_name='automation',
            name='devices_on',
            field=models.ManyToManyField(related_name='automations_on', to='devices.device'),
        ),
        migrations.AddField(
            model_name='automation',
            name='trigger_time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
