# Generated by Django 5.1.5 on 2025-01-21 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0003_alter_intervalreading_homeowner'),
        ('users', '0006_remove_guest_name_guest_house_id_guest_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('joined', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='intervalreading',
            name='homeowner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interval_readings', to='users.owner'),
        ),
    ]
