# Generated by Django 5.1.5 on 2025-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0004_communityevent_alter_intervalreading_homeowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalreading',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervalreading',
            name='usage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
