# Generated by Django 5.1.6 on 2025-02-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_room_room_number'),
        ('energy', '0006_alter_energyusage_period'),
        ('users', '0008_guest_allowed_rooms_guest_departure_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField()),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usages', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='UserEnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField()),
                ('total_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_usages', to='users.owner')),
            ],
        ),
        migrations.DeleteModel(
            name='EnergyUsage',
        ),
    ]
