# Generated by Django 5.1.5 on 2025-02-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_room_room_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbianceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('previous_states', models.JSONField(default=list)),
                ('previous_status', models.JSONField(default=list)),
                ('current_states', models.JSONField(default=list)),
                ('current_status', models.JSONField(default=list)),
                ('devices', models.ManyToManyField(blank=True, related_name='ambiance_modes', to='devices.device')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambiance_modes', to='devices.room')),
            ],
        ),
    ]
